version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/code"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    hostname: redis
    volumes:
      - redis-data:/data

  test:
    build: .
    environment:
      - CI=true
    command: npm test

volumes:
  redis-data:
